More detailed exception messages in `ListenerConfigurationChecker`
yiisoft/yii-event pull request #33
Opened 2021-09-03 19:38 UTC by vjik

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | #31

2021-09-06 10:58 UTC, samdark requested changes

2021-09-06 10:58 UTC, samdark commented on CHANGELOG.md
> +- Enh #32: More detailed exception messages in `ListenerConfigurationChecker` (vjik)
```suggestion
- Enh #32: Use more detailed exception messages in `ListenerConfigurationChecker` (vjik)
```

2021-09-06 10:58 UTC, samdark commented on src/ListenerConfigurationChecker.php
> +                    $definition[1] . '" not exists in him.';
```suggestion
                return sprintf('Could not instantiate "%s" or "%s" method is not defined in this class.', $definition[0], $definition[1]);
```

2021-09-06 10:58 UTC, samdark commented on src/ListenerConfigurationChecker.php
> +                return 'Method "' . $definition[1] . '" not exists in class ' . get_class($definition[0]) . '.';
```suggestion
                return sprintf('"%s" method is not defined in "%s" class.', $definition[1], get_class($definition[0]));
```

2021-09-07 19:46 UTC, vjik commented on CHANGELOG.md
> +- Enh #32: More detailed exception messages in `ListenerConfigurationChecker` (vjik)
Done

2021-09-07 19:46 UTC, vjik commented on src/ListenerConfigurationChecker.php
> +                    $definition[1] . '" not exists in him.';
Done

2021-09-07 19:46 UTC, vjik commented on src/ListenerConfigurationChecker.php
> +                return 'Method "' . $definition[1] . '" not exists in class ' . get_class($definition[0]) . '.';
Done

2021-09-07 20:18 UTC, samdark approved these changes

2021-09-07 20:19 UTC, merged

2021-09-07 20:19 UTC, samdark commented
👍