Add error message when callable is string and cannot be instantiated
yiisoft/yii-event pull request #34
Opened 2021-09-15 10:22 UTC by thenotsoft

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |

2021-09-15 10:49 UTC, samdark approved these changes

2021-09-15 12:37 UTC, vjik requested changes
We can check case when `__invoke()` method exists and create error message without this.

2021-09-16 10:49 UTC, vjik approved these changes

2021-09-18 20:55 UTC, merged

2021-09-18 20:55 UTC, samdark commented
👍