Move events group name to component params (#61)
yiisoft/yii-event pull request #62
Opened 2023-09-15 11:46 UTC by olegbaturin

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #61

2023-09-15 11:46 UTC, olegbaturin commented
For the first consideration

2023-09-15 13:12 UTC, vjik requested changes

2023-09-15 13:12 UTC, vjik commented on config/params-console.php
> +        'eventsGroup' => 'events-console',
```suggestion
        'eventsConfigGroup' => 'events-console',
```

2023-09-15 13:12 UTC, vjik commented on config/params-web.php
> +        'eventsGroup' => 'events-web',
```suggestion
        'eventsConfigGroup' => 'events-web',
```

2023-09-15 13:12 UTC, vjik commented on CHANGELOG.md
> +- Enh #61: Move events group name to component params (@olegbaturin)
```suggestion
- Enh #61: Move events group name to configuration parameters (@olegbaturin)
```

2023-09-17 08:21 UTC, olegbaturin commented
What's wrong with rector?

2023-09-17 13:25 UTC, vjik approved these changes

2023-09-17 13:26 UTC, vjik commented
> What's wrong with rector?

Rector workflow don't work in PR from forks. So far we have not able to solve this problem. May be has idea how fix it?

2023-09-17 13:26 UTC, merged

2023-09-17 13:26 UTC, vjik commented
Thanks 👍

2023-09-17 16:27 UTC, olegbaturin commented
> > What's wrong with rector?
> 
> Rector workflow don't work in PR from forks. So far we have not able to solve this problem. May be has idea how fix it?

maybe helps
https://github.com/actions/checkout/issues/455